### ISSUE TITLE
Invalid facility code Error msg

### ISSUE THREAD

**Issue by tabacha** [uhppoted/uhppote-core#15]
Hi,
when we try to add a new card with the id: 38857wxyz
```
/bin/uhppote-cli put-card 223190abc 38857wxyz 2023-01-01 2060-01-01 1,2,3,4:2 1234
```
We got an error msg:
`ERROR: 388575490: invalid facility code 388`

So we commented out the code:
![image](https://github.com/uhppoted/uhppote-core/assets/1101544/890aa898-f362-44c3-8032-b7a5e6913cea)
and afterwards we can put the card to the controller. 

`abc` and `wxyz` are digits, replaced by us.

**Comment by tabacha** [comment]
Hi,

the model of the cards and the controller I will send you later, after i have this information.
When I convert 388575490 to binary I will get:

`10111001010010011000100000010` this are 28 bits not 26 bits.

We just thinking about moving from our Windows software to uhppoted. We have 300-500 cards in the Windows database, the number of the card looks here the same as in uhppoted.  Also in Event Messages the card looks like this. Perhabs you implement a software switch if a user wants an validation or not?

**Comment by uhppoted** [comment]
Hi,

Your cards are quite possibly Wiegand-34 (32 bits + 2 parity bits) - it's the other common standard. I just wasn't aware that the UHPPOTE controllers supported Wiegand-34 readers because so far all the systems I've run into have been Wiegand-26 (24 bits + 2 parity bits). Interesting! I'm going to have add support for Wiegand-34 where necessary...

re. software switch. Agreed, I think that's probably the best way forward because I'd prefer to keep the card validation where possible (it saves a lot of finger trouble). I need to think about it a bit more but it will probably comprise:

- something like a `--card-format any`  command line override
- a global system configuration parameter to set the allowed formats

Umm, I need to wrap up the changes I'm currently busy with so will probably only get to it next week sometime if that's ok?

**Comment by uhppoted** [comment]
Hi,

After a fair bit of thought (and much reading - it turns out Wiegand-34 is the HID term for a plethora of custom formats) the CLI card validation has been reworked to work as follows:

- it now defaults to _no_ validation (or equivalently _any_ card format) on the grounds that the access controllers are more or less format agnostic
- if required, Wiegand-26 card validation can be enabled by either:
    - setting the `card.format` value in _uhppoted.conf_ to _Wiegand-26_
    - including the _--card-format wiegand-26_ command line argument for `put-card`, e.g.
```
uhppote-cli put-card --card-format wiegand-26 405419896 10058400  2023-01-01 2023-12-31 1,3,4
```
The `--card-format` command line argument overrides the _uhppoted.conf_ setting.

I still need to test this a bit more and the next release is 6-8 weeks away but the version in the _master_ branch should (hopefully) work sufficiently well for your purposes.

Any feedback would be much appreciated!

**Comment by tabacha** [comment]
Hi,

realy good solution. Thank you for your support.

Best Regards
Sven

**Comment by uhppoted** [comment]
Great! Thank you :-) ... I'll leave this open for a bit in case something turns up over the next week or so.

**Comment by uhppoted** [comment]
Going to close this - seems to be ok, but feel free to reopen if anything turns up :-) (the fix will be included in the next release which is some weeks away)
